name: build static

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '14'
      
      - name: build front and back
        run: |
          yarn install
          yarn build
          yarn build-back
        
      - name: copy to static repo
        env: 
          # GITHUB_REPO: gitee.com/whyour/qinglong-static
          GITHUB_REPO: github.com/icepie/ql
        run: |
          mkdir -p static
          cd ./static 
          cp -rf ../dist ./ && cp -rf ../build ./
          git init && git add .
          git config user.name "icepie"
          git config user.email "icepie.dev@gmail.com"
          git commit --allow-empty -m "copy static at $(date +'%Y-%m-%d %H:%M:%S')"
          git push
